services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flashdeal
      POSTGRES_PASSWORD: flashdeal
      POSTGRES_DB: flashdeal
  #    volumes:
  #      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  k6:
    image: grafana/k6:latest
    profiles: [tools]
    volumes:
      - ./scripts:/scripts
    environment:
      - BASE_URL=${BASE_URL:-http://host.docker.internal:3000}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus:latest
    profiles: [observability]
    ports:
      - "9090:9090"
    volumes:
      - ./docs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    profiles: [observability]
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./docs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
