services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flashdeal
      POSTGRES_PASSWORD: flashdeal
      POSTGRES_DB: flashdeal
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
